### ISSUE TITLE
M1 Compatible Installer

### ISSUE THREAD

**Issue by chrisspiegl** [exeldro/obs-downstream-keyer#13]
Hello, are you planning to make this plugin compatible with the future Universal / Apple Silicone builds of OBS?

As far as I know it's already possible and described in some OBS docs.

I tried to install the current version but it does not show up in the M1 OBS version.

Cheers,
Chris

**Comment by pkej** [comment]
Great plug-in, Exeldro. I don't know if this is any help for you, but advanced scene switcher has a build pipeline for QT6 including M1, perhaps some of those Actions might be of help.

https://github.com/WarmUpTill/SceneSwitcher/actions/runs/2854441661

Excellent work all around, thank you

**Comment by exeldro** [comment]
QT6 should be working in the latest test build you can download here:
https://github.com/exeldro/obs-downstream-keyer/actions/runs/2957744843

**Comment by pkej** [comment]
Thank you! worked like a charm.
