### ISSUE TITLE
Problem with latest version on OBS 27.2.4

### ISSUE THREAD

**Issue by jbcurler2010** [exeldro/obs-downstream-keyer#17]
Getting this with the new version on 27.2.4:
11:21:46.060: LoadLibrary failed for '../../obs-plugins/64bit/downstream-keyer.dll': The specified module could not be found.
11:21:46.060: (126)
11:21:46.060: Module '../../obs-plugins/64bit/downstream-keyer.dll' not loaded

**Comment by exeldro** [comment]
The latest version requires OBS 28 for OBS 27 use a previous version

**Comment by jbcurler2010** [comment]
I was looking for an old download but all of your links in the releases section point to the current version. Thanks.

**Comment by exeldro** [comment]
https://obsproject.com/forum/resources/downstream-keyer.1254/history

**Comment by jbcurler2010** [comment]
Thank you, sir! Didn't realize that was there.
