### ISSUE TITLE
Locking Downstream Keyer Allows Edit

### ISSUE THREAD

**Issue by glnces** [exeldro/obs-downstream-keyer#24]
I'm pretty sure the version of this plugin before OBS 28 stopped you from being able to deselect a scene when the lock function is enabled. Below is an example of allowing the scene to be deselected in OBS 28 which the lock function enabled.

![obs64_51MUatwVcV](https://user-images.githubusercontent.com/29066530/204998461-5cef81da-0537-4d09-bcdf-ec783451b096.gif)

**Comment by exeldro** [comment]
The lock icon is used for the tie switch because I could not find a better icon build into OBS.
So it is not supposed to lock, but it should tie the scene change to the scene change of the main output.
