### ISSUE TITLE
Volume addition / increase

### ISSUE THREAD

**Issue by ogmkp** [exeldro/obs-downstream-keyer#30]
Hi there !

When I activate a scene in the DSK and I take this same scene to program, the volume of each source is increased.
I can only hear this trough the encoder, on live and recording.

I have the impression that the volume of SOURCE A in DSK is added to SOURCE A of the same scene that I program.

Do you have an idea ?

DSK is a fantastic plugin, I use it on Linux, now Debian 12.

Thanks !

**Comment by exeldro** [comment]
That is expected behavior to me. When you add the same audio source twice in a single scene the volume is also increased, so adding the audio source twice by having 1 in the program and 1 in the DSK I expect the same behavior.

**Comment by ogmkp** [comment]
If I had two VUmeters from the same source in the sound mixer I would have understood, but it's better that this isn't the case.
It's not a very serious problem, for example, when I put on the sound of an app acquired by NDI and I want to keep this sound when I change scene and then come back to it, I'd like to avoid this addition of volume.
Would it be possible to avoid this for a future release you think?

**Comment by ogmkp** [comment]
@exeldro what do you think about this ?
https://github.com/obsproject/obs-studio/pull/9666

**Comment by exeldro** [comment]
That seems not related to this issue to me.

**Comment by ogmkp** [comment]
I'll close here, as this is a concern that seems to be internal to the OBS engine.
