### ISSUE TITLE
Where does this install on arm64 mac?

### ISSUE THREAD

**Issue by ChristofferSthlm** [exeldro/obs-downstream-keyer#32]
Hey there!

Just installed this plugin on M1 Mac (ARM64). Cannot find the files after installation, and OBS does not find it either. Where are the files (so that I can move them to the correct place) and maybe someone should look over the mac installer.

Cheers!

Christoffer

**Comment by exeldro** [comment]
It should be in `~/Library/Application Support/obs-studio/plugins`

**Comment by exeldro** [comment]
There is no setting to allow plugins. Is it showing in the OBS log file?

**Comment by ChristofferSthlm** [comment]
Looked in the log file and realized the OBS updates had continued to update for intel and not Apple Silicon, so the plugin was not compatible. Problem solved though. Thanks for the help!
