### ISSUE TITLE
Vertical Output Source Crashing OBS 

### ISSUE THREAD

**Issue by Floraviolet** [exeldro/obs-downstream-keyer#33]
If I leave the vertical scene with the vertical output source alone, everything works fine. OBS only crashes when I manipulate sources within the scene that the output source is on. I was able to repeat the crash by re-arranging the order of the sources with the output source on. I believe you have to look at the filters of a source first. When I set the output source as hidden, I believe this issue went away but I haven't tested enough to be certain. I should note I had this issue with and without the vertical downstream keyer active on the scene.

**Comment by exeldro** [comment]
I was able to replicate the issue and made a fix. Can you test if this also fixes it for you?
You can download a test build from the bottom of this page:
https://github.com/exeldro/obs-downstream-keyer/actions/runs/8704501210

**Comment by Floraviolet** [comment]
It seems to be working fine now! Thank you for the quick response!!
