### ISSUE TITLE
obs-websocket vendor request new feature or enhancement (hide a scene)

### ISSUE THREAD

**Issue by Moulaythami** [exeldro/obs-downstream-keyer#35]
Hi @exeldro 

Thanks for your work—it's truly phenomenal.

I have a quick feature request for obs-websocket, regarding obs-downstream-keyer:

Could we add a vendor request to hide a scene, essentially like the 'pause button'?

(Currently, we can use the hotkey, it work smoothly already and I can live with that.)

Thanks for considering it.

Best,
Moulaythami

**Comment by eanderson143** [comment]
Second the websocket vendor request for setting a certain DSK to "None" (like the pause).

Maybe call framed as:
{"vendorName":"downstream-keyer","requestType":"dsk_clear", "requestData": {"dsk_name":"DSK 1"}}
or
{"vendorName":"downstream-keyer","requestType":"dsk_select_scene", "requestData": {"dsk_name":"DSK 1","set":"null_scene"}}
or
{"vendorName":"downstream-keyer","requestType":"dsk_select_scene", "requestData": {"dsk_name":"DSK 1","clear":"add whatever that would be fitting"}}

Just a thought - I also just use the hotkey method right now, but it would be nice to be able to not muddle up keyboard commands with hotkeys. It would also be awesome if you were able to include the websocket commands in the readme or in a secondary readme file. I stumbled across them in a forum post and finally found the "Update" notes. (https://obsproject.com/forum/threads/downstream-keyer.142247/post-605063)

FYI, this plugin is one of the main reasons I am able to use OBS for my setup!

**Comment by Moulaythami** [comment]
<img width="671" alt="image" src="https://github.com/exeldro/obs-downstream-keyer/assets/49905667/c52ecff9-7d6d-4421-894f-953a77f02899">

```json

{
  "vendorName": "downstream-keyer",
  "requestType": "dsk_select_scene",
  "requestData": {
    "dsk_name": "DSK 1",
    "scene": ""
  }
}

That's it! It works.

Thank you @eanderson143 
And thank you @exeldro because it was already working, you are a great developer I cannot express how much I admire your work.

**Comment by Moulaythami** [comment]
<img width="671" alt="image" src="https://github.com/exeldro/obs-downstream-keyer/assets/49905667/c52ecff9-7d6d-4421-894f-953a77f02899">

```json

{
  "vendorName": "downstream-keyer",
  "requestType": "dsk_select_scene",
  "requestData": {
    "dsk_name": "DSK 1",
    "scene": ""
  }
}

```

That's it! It works.

Thank you @eanderson143 
And thank you @exeldro because it was already working, you are a great developer I cannot express how much I admire your work.
