### ISSUE TITLE
Feature request: "hide after XX ms"

### ISSUE THREAD

**Issue by studiokrause** [exeldro/obs-downstream-keyer#46]
I use OBS-DSK for showing lower thirds. Can you add an option to automatically run selected" hide" transition after desired time (and ie. back to "None/Empty" DSK scene or "paused" state?). Like setting overlay duration in VMix.

**Comment by exeldro** [comment]
Do you need the ms or will seconds do fine for you?

**Comment by studiokrause** [comment]
The whole OBS uses miliseconds, so maybe ms?

**Comment by studiokrause** [comment]
Thanks! Works perfect!
