### ISSUE TITLE
[Feature Request] Add obs Vendor to create/remove/rename DSK

### ISSUE THREAD

**Issue by TooPick** [exeldro/obs-downstream-keyer#47]
Hi ! 

I'm currently coding something that uses Downstream Keyer with websockets to automate global scenes creation and I wanted to know if it's possible to register a new vendor. 
I actually can add a new scene to an existing DSK with websockets using the CallVendorRequest request with the following parameter 'dsk_add_scene', but I think there are no way to add or remove a DSK with code. 
Can you add this vendor ? I don't know C++ very well so I can't make a pull request but if think it's not that difficult.
Or maybe there is already a way to add or delete DSK with code that I don't found.

Thank you in advance !

Sorry for my english, is not my primary langage.

**Comment by exeldro** [comment]
[`dsk_remove_scene`](https://github.com/exeldro/obs-downstream-keyer/blob/ab6ccaca2b8fdddf576e3a952841ad20aa826cfd/downstream-keyer-dock.cpp#L192) exists, is that what you are looking for?

**Comment by TooPick** [comment]
Not exactly. I think my explanation was bad... I'm looking for a way to create a new tab like the one that is named "DSK 1" by default using my code to have a tab named "MY APP DSK" for example.

**Comment by exeldro** [comment]
Ah, that should be something that is possible to add.

**Comment by TooPick** [comment]
Also I have a question, do you think these calls will work if the dock is not displayed in OBS ? When I'm looking at the code I think it's unregistered when the dock is close but I'm not sure.
