### ISSUE TITLE
Add support for transition-table

### ISSUE THREAD

**Issue by ItsFlo** [exeldro/obs-downstream-keyer#6]
I would like to use different transitions for each scene in one DSK just how your transition-table works.
These rules don´t work in the DSK though.

My suggested solution would be a new transition option "Default" that falls back to the transition that is currently selected in OBS and can be overwritten by the transition table (how transitioning the Program works).
Overwriting the transition for showing and hiding would be set by the to and from "Any" rules.

**Comment by exeldro** [comment]
Good idea of supporting transition table in downstream keyer will check what is possible.

**Comment by exeldro** [comment]
Added in version 0.2.7
