### ISSUE TITLE
downstream-keyer.so: undefined symbol: _ZTI15DownstreamKeyer

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-downstream-keyer#7]
Hi @exeldro,

Thanks for your work around plugins for OBS.

I already made available move-transition in Debian[1].

[1] https://tracker.debian.org/pkg/obs-move-transition

Now, I am packaging downstream-keyer against libobs-dev. There is an issue blocking  the loading in OBS:
```

$ obs 2>&1 | grep keyer
error: os_dlopen(/usr//lib/x86_64-linux-gnu/obs-plugins/downstream-keyer.so->/usr//lib/x86_64-linux-gnu/obs-plugins/downstream-keyer.so): /usr//lib/x86_64-linux-gnu/obs-plugins/downstream-keyer.so: undefined symbol: _ZTI15DownstreamKeyer
warning: Module '/usr//lib/x86_64-linux-gnu/obs-plugins/downstream-keyer.so' not loaded
```

Thanks in advance for a solution.

Cheers,

Eriberto

**Comment by eribertomota** [comment]
Complementing, libobs-dev 27.1.3.

Taking advantage of this message, what is the minimum OBS version for this plugin? Is it compatible with OBS 26?

**Comment by eribertomota** [comment]
Today I tested the plugin after build it inside OBS. The same problem. Could you check this issue?

**Comment by exeldro** [comment]
@eribertomota the latest version of this plugin requires OBS version 27.1.x or higher
I have no idea what the issue could be.

**Comment by eribertomota** [comment]
@exeldro I am using 27.1.3. Now I found #3, saying about the same issue. I am using a jail, a fresh and updated system. GCC-11.

**Comment by eribertomota** [comment]
Could you try to rebuild the plugin and load it in OBS? It is not loading.

$ obs 2>&1 | grep keyer

**Comment by exeldro** [comment]
Tested on windows, build with visual studio 17 without a problem

**Comment by eribertomota** [comment]
The problem is when loading with OBS, not when building. On Linux, the plugin builds fine.

If not possible for you to test it under a Linux VM, the plugin won't be compatible with Linux. Please, allows us to use this fantastic plugin on Linux.

I attached a complete log from OBS.

Thanks in advance.

[log-obs-dsk-20211205.txt](https://github.com/exeldro/obs-downstream-keyer/files/7656844/log-obs-dsk-20211205.txt)

**Comment by ahfauth** [comment]
Hi @exeldro !

Just seen this discussion here.

I love all your plugins and it would be great if this one was also available on Debian repository. Would it be possible to check what can be done?

Thank you!

**Comment by exeldro** [comment]
Because of my lack of Linux knowledge it would take me a lot of time, which I don't have at the moment. Hopefully somebody with more Linux experience can help here.

**Comment by talau** [comment]
Hi there!

To fix the issue on Linux is need to enable Meta-Object Compiler (moc).

Thanks to @eribertomota for the validation tests with the pull request below.
