### ISSUE TITLE
 Please, provide tags to allow packaging

### ISSUE THREAD

**Issue by eribertomota** [exeldro/obs-downstream-keyer#9]
Hi @exeldro,

Today I sent the obs-downstream-keyer to Debian. Now I need a tag for each release, like in move-transition. Without a tag, I will need to discover what was the last commit for the last release. Another problem is without a tag Debian won't be able to search for new releases to be packaged.

Cheers,

Eriberto

**Comment by exeldro** [comment]
tag/release 0.2.1 is now created on GitHub
